
from .style import (
    apply_paper_style,
    get_figure_size,
    get_mode_color,
    get_sector_color,
    get_horizon_color,
    MODE_COLORS,
    SECTOR_COLORS,
    HORIZON_COLORS,
    REGIME_COLORS,
    FIGURE_SIZES,
    format_percent_axis,
    format_date_axis,
    add_recession_shading,
    add_regime_zones,
    annotate_max_drawdown,
    annotate_sharpe,
)

from .performance_curves import (
    plot_equity_curves,
    plot_equity_by_horizon,
    plot_drawdowns,
    plot_underwater,
    plot_rolling_sharpe,
    plot_rolling_volatility,
    plot_relative_performance,
    plot_return_distribution,
)

from .regime_curves import (
    plot_vix_with_zones,
    plot_regime_timeline,
    plot_performance_by_regime,
    plot_regime_heatmap,
    plot_regime_transitions,
    plot_expectation_decomposition,
    build_regime_series,
    VIX_ZONES,
)

from .model_metrics import (
    plot_ic_time_series,
    plot_ic_distribution,
    plot_ic_by_horizon,
    plot_sharpe_comparison,
    plot_metrics_heatmap,
    plot_rmse_comparison,
    plot_prediction_vs_actual,
    plot_feature_importance,
    plot_quantile_returns,
)

from .data_inputs import (
    plot_sector_returns,
    plot_sector_correlations,
    plot_sector_rolling_correlations,
    plot_feature_correlation_matrix,
    plot_feature_distributions,
    plot_feature_time_series,
    plot_missing_data,
    plot_label_distribution,
    plot_summary_statistics,
)

from .paper_tables import (
    generate_strategy_comparison_table,
    generate_horizon_comparison_table,
    generate_ic_summary_table,
    generate_regime_performance_table,
    generate_model_summary_table,
    generate_feature_importance_table,
    generate_paired_comparison_table,
    generate_turnover_table,
    generate_full_results_table,
    format_percent,
    format_float,
    add_significance_stars,
)

__all__ = [
    "apply_paper_style",
    "get_figure_size",
    "get_mode_color",
    "get_sector_color",
    "get_horizon_color",
    "MODE_COLORS",
    "SECTOR_COLORS",
    "HORIZON_COLORS",
    "REGIME_COLORS",
    "FIGURE_SIZES",
    "format_percent_axis",
    "format_date_axis",
    "add_recession_shading",
    "add_regime_zones",
    "annotate_max_drawdown",
    "annotate_sharpe",
    "plot_equity_curves",
    "plot_equity_by_horizon",
    "plot_drawdowns",
    "plot_underwater",
    "plot_rolling_sharpe",
    "plot_rolling_volatility",
    "plot_relative_performance",
    "plot_return_distribution",
    "plot_vix_with_zones",
    "plot_regime_timeline",
    "plot_performance_by_regime",
    "plot_regime_heatmap",
    "plot_regime_transitions",
    "plot_expectation_decomposition",
    "build_regime_series",
    "VIX_ZONES",
    "plot_ic_time_series",
    "plot_ic_distribution",
    "plot_ic_by_horizon",
    "plot_sharpe_comparison",
    "plot_metrics_heatmap",
    "plot_rmse_comparison",
    "plot_prediction_vs_actual",
    "plot_feature_importance",
    "plot_quantile_returns",
    "plot_sector_returns",
    "plot_sector_correlations",
    "plot_sector_rolling_correlations",
    "plot_feature_correlation_matrix",
    "plot_feature_distributions",
    "plot_feature_time_series",
    "plot_missing_data",
    "plot_label_distribution",
    "plot_summary_statistics",
    "generate_strategy_comparison_table",
    "generate_horizon_comparison_table",
    "generate_ic_summary_table",
    "generate_regime_performance_table",
    "generate_model_summary_table",
    "generate_feature_importance_table",
    "generate_paired_comparison_table",
    "generate_turnover_table",
    "generate_full_results_table",
    "format_percent",
    "format_float",
    "add_significance_stars",
]
